name: Run PHP Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs at 0, 5, 10, 15, etc.
    - cron: '2-59/5 * * * *'  # Runs at 2, 7, 12, 17, etc.

jobs:
  run-php-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Change if needed

      - name: Run PHP Script
        run: php system-ka.php
